INSERT INTO category(description) values('American')
INSERT INTO category(description) values('Italian')
INSERT INTO category(description) values('Mexican')
INSERT INTO category(description) values('Fast Food')
INSERT INTO unit_of_measure(description) values('Teaspoon')
INSERT INTO unit_of_measure(description) values('Tablespoon')
INSERT INTO unit_of_measure(description) values('cup')
INSERT INTO unit_of_measure(description) values('pinch')
INSERT INTO unit_of_measure(description) values('ounce')